- hosts: all
  become: true

  tasks:
        
  - name: donetcore
    docker_container:
      name: 'donetcore1'
      recreate: true
      restart_policy: unless-stopped
      image: 'mcr.microsoft.com/dotnet/samples:dotnetapp'
      published_ports:
        - "8000:80"

  - name: mysql
    docker_container:
      name: 'mysql1'
      recreate: true
      restart_policy: unless-stopped
      image: 'mysql:8.0'
      env:
        MYSQL_ROOT_PASSWORD: "secret_root"
        MYSQL_DATABASE: "db"
        MYSQL_USER: "db_user"
        MYSQL_PASSWORD: "secret_user"
      published_ports:
        - "3306:3306"
        